### ISSUE TITLE
Error: @next/font/local failed to run or is incorrectly configured

### ISSUE THREAD

**Issue by ricsands2801** [vercel/geist-font#16]
**Font Name (Geist Sans/Geist Mono):**
- [ X] Geist Sans
- [ X] Geist Mono

**Description of the Issue:**
Running nextjs 13.5.6 (or 14) and get the following after installing the font.  Inter font via next/font works correctly

Error: @next/font/local failed to run or is incorrectly configured.
If you just installed `@next/font`, please try restarting `next dev` and resaving your file.

A restart does not resolve

**Steps to Reproduce:**
1. install geist font
2. add to layout
3. run dev

**Expected Behavior:**
Font works

**Environment (please complete the following information):**
 - Nextjs 13.5.6
 - node 21
 - pnpm
 - geist 1.0
 - turborepo

**Comment by mwskwong** [comment]
I guess it is an issue of how `localFont` works.

In short, this error will be thrown if importing the font to a client component/function. The workaround (or maybe this is how it is supposed to be used?) is to import it to a server component, e.g., root layout and make use of the CSS variable, if needed.

**Comment by eyenalxai** [comment]
```
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={GeistSans.className}>
        <main className={cn('container', 'mx-auto', 'max-w-xl')}>
          {children}
        </main>
      </body>
    </html>
  )
}
```

Still the same error :( 

Above RootLayout I have metadata and viewport,

**Comment by eyenalxai** [comment]
```
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={GeistSans.className} suppressHydrationWarning>
      <body>
        <main className={cn('container', 'mx-auto', 'max-w-xl')}>
          {children}
        </main>
      </body>
    </html>
  )
}
```

Still the same error :( 

Above RootLayout I have metadata and viewport,

**Comment by ricsands2801** [comment]
I would expect a font to work outside of server side.

No difference though if switched to server

**Comment by esau-morais** [comment]
The issue is with turbo. I was running `next dev --turbo` and just needed to remove the argument to prevent the error

**Comment by mhughdo** [comment]
Removing the `--turbo` flag in the `next dev` command also did the trick for me

**Comment by ricsands2801** [comment]
I have no turbo flag with error remaining

**Comment by 4Furki4** [comment]
I faced the same issue even if I didn't run my app with the turbo flag. It seems that we can't use Geist fonts in client components because It was throwing the error in my root layout which is a client component but now I can use the fonts in a layout of [route groups](https://nextjs.org/docs/app/building-your-application/routing/route-groups) which is a server component. Looking for the support of using geist fonts in client components!

Last but not least, the other workaround is [downloading the Geist font files](https://github.com/vercel/geist-font/releases) and using them with [localFont function](https://nextjs.org/docs/app/building-your-application/optimizing/fonts#api-reference).

**Comment by tinrab** [comment]
Same issue. I'm trying to get it to work with Storybook.
```
ReferenceError: __dirname is not defined
    next geist_font.js:1273
    next geist_font.js:1276
    __require2 chunk-AUZ3RYOM.js:18
    pnpm geist_font.js:1622
    __require2 chunk-AUZ3RYOM.js:18
    <anonymous> font.js:1
runtime.js:4:101006
    error http://localhost:6006/sb-preview/runtime.js:4
    renderPreviewEntryError http://localhost:6006/sb-preview/runtime.js:89
    renderPreviewEntryError http://localhost:6006/sb-preview/runtime.js:103
    getProjectAnnotationsOrRenderError http://localhost:6006/sb-preview/runtime.js:87
    _runRejections http://localhost:6006/sb-preview/runtime.js:4
    _runRejections http://localhost:6006/sb-preview/runtime.js:4
    _setRejected http://localhost:6006/sb-preview/runtime.js:4
    _failWith http://localhost:6006/sb-preview/runtime.js:4
    _runRejections http://localhost:6006/sb-preview/runtime.js:4
    _runRejections http://localhost:6006/sb-preview/runtime.js:4
    _setRejected http://localhost:6006/sb-preview/runtime.js:4
    _failWith http://localhost:6006/sb-preview/runtime.js:4
    _chainPromiseData http://localhost:6006/sb-preview/runtime.js:4
```

**Comment by JohnPhamous** [comment]
#37 should fix this!

**Comment by nagman** [comment]
I've just installed it (`1.1.0`) and I get:
```
next_font_local__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function
```
in Storybook `7.5.3`.

I think I'll just stick to the `localFont` method, as suggested by @4Furki4

**Comment by 4Furki4** [comment]
> I've just installed it (`1.1.0`) and I get:
> ```
> next_font_local__WEBPACK_IMPORTED_MODULE_0___default(...) is not a function
> ```
> in Storybook `7.5.3`.
> 
> I think I'll just stick to the `localFont` method, as suggested by @4Furki4 

Hey dude.
I was having the same issue today when I try to run my application in dev mode using turbopack. Fortunately, updating my next version to 14.0.3 solved the issue. Hope it does the trick for you as well.

**Comment by nagman** [comment]
Alas... it did not do the trick :/
I've just updated next from `14.0.1` to `14.0.3` and I still have the exact same error with Storybook.

**Comment by tobiaszkrolak** [comment]
Inside NextJS everything is alright, but in Storybook i also experienced: "TypeError:next_font_local__WEBPACK_IMPORTED_MODULE_0___default(...)"

Next.js 14.0.3
Geist 1.2.0
Yarn 3.6.4
Node 18.14

**Comment by ugamestudio** [comment]
The error is still there

**Comment by bluebreadhead** [comment]
The devs don't care

**Comment by ChristopherGladyshev** [comment]
If you encounter a similar issue while running jest tests, you can follow these steps.

create 
// jest.setup.ts
```
jest.mock('@next/font/local', () => ({
  __esModule: true,
  default: () => ({
    className: 'mock-font-class',
    style: { fontFamily: 'MockFont' },
  }),
}));

jest.mock('@next/font/google', () => ({
  __esModule: true,
  Oswald: () => ({
    className: 'mock-google-font-class',
    style: { fontFamily: 'MockGoogleFont' },
  }),
}));
```
// jest.config.ts
```
export default {
  preset: 'ts-jest',
  testEnvironment: 'jsdom',
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  transform: {
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': '@nx/react/plugins/jest',
    '^.+\\.[tj]sx?$': ['babel-jest', { presets: ['@nx/next/babel'] }],
  },
};

```
